---
# Task to configure ulimits and THP for Splunk
- name: Set ulimits for splunk
  ansible.builtin.template:
    src: splunk_ulimits.conf.j2
    dest: /etc/security/limits.d/splunk_ulimits.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  when: splunk_use_initd

- name: Disable THP
  ansible.builtin.include_tasks: configure_thp.yml
  when:
    - ansible_service_mgr == "systemd"
    - ansible_connection != "docker"
    - "'full' in group_names"

- name: Enable read for dmesg
  ansible.builtin.include_tasks: configure_dmesg.yml
  when: configure_dmesg

- name: Configure firewall service
  ansible.builtin.include_tasks: "configure_firewall.yml"
  when:
    - firewall_service != 'undefined'
    - configure_firewall != false
    - "'full' in group_names"
