---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - .yamllint

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 2
    min-spaces-inside-empty: 0
  colons: disable
  commas: enable
  comments:
    min-spaces-from-content: 1
    level: warning
  comments-indentation: false
  #    level: warning
  document-end: disable
  document-start:
    ignore: |
      **/**/vault.yml
    level: warning
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  # When using `ansible-galaxy init ..` the newline is removed
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  quoted-strings: disable
  trailing-spaces: enable
  truthy: { allowed-values: ["true", "false"] }
