---
- name: Stop Splunkd service
  include_tasks: splunk_stop.yml

- name: Clean KVStore
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk clean kvstore --local --answer-yes"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: clean_result
  changed_when: clean_result.rc == 0
  failed_when: clean_result.rc != 0
  notify:
    - start splunk
