---
- name: Adhoc KVStore Backup
  block:
  - name: Check if authenticated
    include_tasks: splunk_login.yml
    when: not splunk_authenticated

  - name: Check if we're okay to backup
    ansible.builtin.command: |
      {{ splunk_home }}/bin/splunk show kvstore-status | grep backupRestoreStatus | sed -r 's/\s+backupRestoreStatus : //g'
    register: splunk_kvstore_pre_backup_status_out
    until: "{{ splunk_kvstore_pre_backup_status_out.stdout }} == 'Ready'"

  - name: Backup KVStore on desired host
    ansible.builtin.command: |
      {{ splunk_home }}/bin/splunk backup kvstore {{ archive_name | default("") }}
    register: splunk_kvstore_backup_out
    changed_when: splunk_kvstore_backup_out.rc == 0
    failed_when: splunk_kvstore_backup_out.rc != 0

  - name: Check that backup has finished
    ansible.builtin.shell: |
      {{ splunk_home }}/bin/splunk show kvstore-status | grep backupRestoreStatus | sed -r 's/\s+backupRestoreStatus : //g'
    register: splunk_kvstore_status_out
    until: "{{ splunk_kvstore_status_out.stdout }} == 'Ready'"

  become: true
  become_user: "{{ splunk_nix_user }}"
