---
- name: Stop Splunk
  include_tasks: splunk_stop.yml

- name: Clean KVStore
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk clean kvstore --local --answer-yes"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: clean_result
  changed_when: clean_result.rc == 0
  failed_when: clean_result.rc != 0

- name: Edit server.conf to increase the oplogSize setting
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: kvstore
    option: oplogSize
    value: "{{ splunk_oplog_size }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  become_user: "{{ splunk_nix_user }}"

- name: Start Splunk to trigger synchronisation
  include_tasks: splunk_start.yml

# sets fact splunk_kvstore_status_json
- name: Verify synchronisation with show kvstore-status
  include_tasks: get_kvstore_status.yml
  until: "'{{ splunk_kvstore_status_json.status }}' == 'ready'"
  delay: 10
  retries: 30
