---
- name: Stop Splunk
  ansible.builtin.include_tasks: splunk_stop.yml

- name: Clean dispatch directory of all files
  ansible.builtin.command: "rm -rf {{ splunk_home }}/var/run/splunk/dispatch/*"
  become: true

- name: Start Splunk
  ansible.builtin.include_tasks: splunk_start.yml
