---
- name: Run splunk version command to check currently installed version
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk version --answer-yes --auto-ports --no-prompt --accept-license"
  register: current_version
  become: true
  become_user: "{{ splunk_nix_user }}"
  changed_when: false
  check_mode: false

- name: Get Splunk version number only
  ansible.builtin.set_fact:
    splunk_version_release: "{{ current_version.stdout | regex_search('(\\d\\.\\d+\\.[^\\s]+)') }}"
