---
- name: Run splunk version command to check currently installed version
  include_tasks: check_splunk_version.yml

# Splunk version >= 8.1 supports mode=peer
# https://docs.splunk.com/Documentation/Splunk/latest/Indexer/ConfigurepeerswithCLI
# Splunk version < 8.1 supports mode=slave
# https://docs.splunk.com/Documentation/Splunk/8.0.9/Indexer/ConfigurepeerswithCLI
- name: Setting clustering mode based on Splunk version number
  set_fact:
    mode_value: "{{ splunk_version_release is version('8.1', '<') | ternary('slave', 'peer') }}"
    manager_uri_call: "{{ splunk_version_release is version('8.1', '<') | ternary('master_uri', 'manager_uri') }}"

# TODO: Pre check if cluster settings are different, because this always needs a restart
- name: Configure idxc member
  command: "{{ splunk_home }}/bin/splunk edit cluster-config -mode {{ mode_value }} {% if splunk_idxc_multisite %}-site {{ splunk_idxc_site_affinity }}{% endif %} -auth {{ splunk_auth }} -{{ manager_uri_call }} {{ splunk_uri_cm }} -replication_port {{ splunk_idxc_rep_port }} -secret {{ splunk_idxc_key }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: idxc_peer_init_result
  changed_when: idxc_peer_init_result.rc == 0
  failed_when: idxc_peer_init_result.rc != 0
  notify:
    - restart splunk
    - wait for splunkd
  no_log: false
  until: idxc_peer_init_result.rc == 0
  retries: 6
  delay: 5
