---
- name: Update the systemd file for Splunk
  ini_file:
    path: "/etc/systemd/system/{{ splunk_service }}.service"
    section: Service
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
  become: true
  loop:
    - { option: "LimitNOFILE", value: "1024000" }
    - { option: "LimitNPROC", value: "512000" }
    - { option: "LimitFSIZE", value: "infinity" }
    - { option: "LimitDATA", value: "infinity" }
    - { option: "LimitCORE", value: "infinity" }
    - { option: "TasksMax", value: "infinity" }
  notify: reload systemctl daemon
