---
- name: Install .bashrc and .bash_profile files
  template:
    src: "{{ item.bashtemplate }}"
    dest: "{{ splunk_home }}/{{ item.bashfilepath }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  loop:
    - { bashtemplate: "{{ splunk_bashrc_template }}", bashfilepath: '.bashrc' }
    - { bashtemplate: "{{ splunk_bash_profile_template }}", bashfilepath: '.bash_profile' }
