---
# Allow users to run dmesg. This is needed for the Splunk_TA_nix to run scripts
- name: Add sysctl for dmesg
  sysctl:
    name: kernel.dmesg_restrict
    value: '0'
    state: present
    sysctl_file: /etc/sysctl.d/20-splunk.conf
    reload: yes
  register: sysctl_dmesg
  become: true

- name: Restart procps
  service:
    name: procps
    state: restarted
  # RHEL does not have the procps service.
  when: sysctl_dmesg.changed and ansible_os_family == 'Debian'
  become: true
