---
- name: Configure file access control list (facl) settings for splunk user
  block:
    - name: Set default facl to allow splunk user to read /var/log
      acl:
        path: /var/log
        entity: "{{ splunk_nix_user }}"
        etype: user
        permissions: rx
        default: "{{ item }}"
        recursive: true
        state: present
      become: true
      loop:
        - true
        - false

    - name: Add logrotate script to enforce splunk user facls
      template:
        src: splunk_facl.j2
        dest: /etc/logrotate.d/splunk_facl
        owner: root
        group: root
      become: true

    - name: Check if auditd.conf is present
      stat:
        path: /etc/audit/auditd.conf
      register: result_auditd_conf
      become: true

    - name: Allow splunk to read /var/log/audit.log
      ini_file:
        path: /etc/audit/auditd.conf
        section: null
        option: log_group
        value: "{{ splunk_nix_group }}"
      become: true
      notify:
        - restart redhat auditd service
        - restart non-redhat auditd service
      when: result_auditd_conf.stat.exists

  when: splunk_nix_user != 'root'
