---
- name: Run splunk version command to check currently installed version
  include_tasks: check_splunk_version.yml

- name: Set IDXC Values
  include_tasks: set_idxc_facts.yml

- name: Configure idxc member
  command: "{{ splunk_home }}/bin/splunk edit cluster-config -mode {{ peer_mode_value }} -auth {{ splunk_auth }} -{{ manager_uri_value }} {{ splunk_uri_cm }} -replication_port {{ splunk_idxc_rep_port }} -secret {{ splunk_idxc_key }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: idxc_peer_init_result
  changed_when: idxc_peer_init_result.rc == 0
  failed_when: idxc_peer_init_result.rc != 0
  notify: restart splunk
  no_log: true
  until: idxc_peer_init_result.rc == 0
  retries: 6
  delay: 5
