---
- name: Configure file access control list (facl) settings for splunk user
  block:
    - name: Install acl package
      package:
        name: "acl"
        state: present
      become: True
    - name: Set default facl to allow splunk user to read /var/log
      acl:
        path: /var/log
        entity: "{{ splunk_nix_user }}"
        etype: user
        permissions: rx
        default: "{{ item }}"
        recursive: true
        state: present
      become: true
      loop:
        - true
        - false

    - name: Add setfacl to logrotate script
      lineinfile:
        path: "{{ logrotate_file }}"
        insertbefore: 'endscript'
        line: '        /usr/bin/setfacl -Rm u:{{ splunk_nix_user }}:rx /var/log'
      become: True

    - name: Check if auditd.conf is present
      stat:
        path: /etc/audit/auditd.conf
      register: result_auditd_conf
      become: true

    - name: Allow splunk to read /var/log/audit.log
      ini_file:
        path: /etc/audit/auditd.conf
        section: null
        option: log_group
        value: "{{ splunk_nix_group }}"
      become: true
      notify:
        - restart redhat auditd service
        - restart non-redhat auditd service
      when: result_auditd_conf.stat.exists

  when: not least_privileged
