---
- name: Run splunk version command to check currently installed version
  include_tasks: check_splunk_version.yml

# Splunk version < 8.1 supports mode=master
# https://docs.splunk.com/Documentation/Splunk/8.0.9/Indexer/Configuremasterwithserverconf
# Splunk version >= 8.1 supports mode=manager
# https://docs.splunk.com/Documentation/Splunk/latest/Indexer/Configuremanagerwithserverconf
- name: Setting clustering mode based on Splunk version number
  set_fact:
    mode_value: "{{ splunk_version_release is version('8.1', '<') | ternary('master', 'manager') }}"

- name: Setting site affinity of cluster manager if not set
  set_fact:
    site_affinity: "{% if splunk_idxc_multisite and splunk_idxc_site_affinity == 'site0' %}site1{% else %}{{ splunk_idxc_site_affinity }}{% endif %}"

- name: Extract encrypted value
  include_tasks: check_decrypted_secret.yml
  vars:
    req_secret_conf: server
    req_secret_section: clustering
    req_secret_option: pass4SymmKey

- name: Configure clustering stanza for cluster manager node
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: clustering
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: 
    - restart splunk
    - wait for splunkd
  no_log: false
  loop:
    - { option: "mode", value: "{{ mode_value }}" }
    - { option: "replication_factor", value: "{{ splunk_idxc_rf }}" }
    - { option: "search_factor", value: "{{ splunk_idxc_sf }}" }
    - { option: "cluster_label", value: "{{ splunk_idxc_label }}" }
    - { option: "multisite", value: "{{ splunk_idxc_multisite | ternary('true', 'false') }}" }
    - { option: "available_sites", value: "{{ splunk_idxc_available_sites }}" }
    - { option: "site_replication_factor", value: "{{ splunk_idxc_site_rf }}" }
    - { option: "site_search_factor", value: "{{ splunk_idxc_site_sf }}" }
    - { option: "site_mappings", value: "{{ splunk_idxc_site_mappings }}" }

- name: Configure clustering stanza psk for cluster manager node
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: clustering
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  when:
    - splunk_idxc_key != "undefined"
    - encrypted_secret_value.stdout == "" or (splunk_idxc_key != decrypted_secret_value.stdout | default(''))
  notify: 
    - restart splunk
    - wait for splunkd
  no_log: true
  loop:
    - { option: "pass4SymmKey", value: "{{ splunk_idxc_key }}" }

- name: Configure general stanza on manager node
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: general
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: 
    - restart splunk
    - wait for splunkd
  no_log: true
  when:
    - splunk_idxc_multisite
  loop:
    - { option: "site", value: "{{ site_affinity }}" }
