---
- name: Disable KVStore
  when:
    - ansible_system == "Linux"
    - not splunk_enable_kvstore
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: kvstore
    option: disabled
    value: "true"
  become: True
  become_user: "{{ splunk_nix_user }}"
