---
# Gets SHC captain management domain - like splunk_captain.example
- name: Check if authenticated
  include_tasks: splunk_login.yml
  when: not splunk_authenticated

- name: Get current SHCluster captain
  ansible.builtin.command: |
    {{ splunk_home }}/bin/splunk show shcluster-status | grep -A6 Captain | grep mgmt_uri | sed -r 's/\s+mgmt_uri : //g' | sed -Er 's/http(s)?:\/\///' | sed -Er 's/:[0-9]+//'
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: splunk_get_shcaptain
  changed_when: false
  failed_when: splunk_get_shcaptain.rc != 0

- name: Register SHCluster captain fact
  ansible.builtin.set_fact:
    splunk_shc_captain: "{{ splunk_get_shcaptain.stdout }}"
