---
- name: Start splunk
  service:
    name: "{{ splunk_service }}"
    state: started
  become: true

- name: Reset splunk_authenticated variable
  ansible.builtin.set_fact:
    splunk_authenticated: false
