---
- name: apply shcluster-bundle
  ansible.builtin.command: |
    {{ splunk_home }}/bin/splunk apply shcluster-bundle -preserve-lookups true --answer-yes -auth '{{ splunk_auth }}' {{ extra_args }} -target {{ deploy_target }}
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: apply_shcluster_bundle_result
  changed_when: apply_shcluster_bundle_result.rc == 0
  failed_when: apply_shcluster_bundle_result.rc != 0
  retries: "{{ splunk_apply_shcluster_bundle_retries }}"
  delay: "{{ splunk_apply_shcluster_bundle_delay }}"
  no_log: true
  when: "'shdeployer' in group_names and deploy_target is defined"
  vars:
    deploy_target: "{{ deploy_target | default(''.join(('https://', groups[target_shc_group_name] | first ))) }}"
    extra_args: "{{ extra_args | default('') }}"
