---
- name: "{{ ru_state }} rolling upgrade on cluster manager"
  ansible.builtin.uri:
    url: "{{ splunk_uri_cm }}/services/cluster/manager/control/control/rolling_upgrade_{{ ru_state }}"
    method: POST
    user: "{{ splunk_admin_username }}"
    password: "{{ splunk_admin_password }}"
    force_basic_auth: true
    validate_certs: "{{ splunk_validate_certs | default(false) }}"
    status_code: 200
  no_log: true
  when:
    - ru_state is defined
    - "'clustermanager' in group_names"
