---
# Simple test environment - 2 nodes: 1 indexer + 1 license server (also search head)
all:
  vars:
    ansible_user: ansible
  children:
    full:
      children:
        licensemaster:
          hosts:
            splunk-license:
              # License master + DMC + Search Head

        indexer:
          hosts:
            splunkapp-prod01:
              # Single indexer (no clustering)

        search:
          hosts:
            splunk-license:  # License server also acts as search head

    ansible_controller:
      hosts:
        ansible-controller:
          ansible_user: ansible
