global_bashrc: /etc/bashrc
chk_config_cmd: chkconfig --add disable-thp
linux_packages_default:
  - sysstat
  - telnet
  - tcpdump
  - htop
  - lsof
  - policycoreutils-python
  - policycoreutils
  - gdb
  - bind-utils
linux_packages: "{{ linux_packages_custom | default(linux_packages_default) }}"
