---
global_bashrc: /etc/bash.bashrc
linux_packages:
  - nload
  - iotop
  - iftop
  - sysstat
  - telnet
  - tcpdump
  - htop
  - atop
  - lsof
  - policycoreutils
  - nethogs
  - gdb
  - dnsutils
firewall_service: ufw
logrotate_file: /etc/logrotate.d/rsyslog
