---
global_bashrc: /etc/bash.bashrc
linux_packages_default:
  - nload
  - iotop
  - iftop
  - sysstat
  - telnet
  - tcpdump
  - htop
  - atop
  - lsof
  - policycoreutils
  - nethogs
  - gdb
  - dnsutils
linux_packages: "{{ linux_packages_custom | default(linux_packages_default) }}"
firewall_service: ufw
logrotate_file: /etc/logrotate.d/rsyslog
