---
global_bashrc: /etc/bash.bashrc
linux_packages_default:
  - nload
  - iotop
  - iftop
  - sysstat
  - telnet
  - tcpdump
  - htop
  - atop
  - lsof
  - policycoreutils-python
  - policycoreutils
  - nethogs
  - gdb
  - bind-utils
linux_packages: "{{ linux_packages_custom | default(linux_packages_default) }}"
