---
# Example playbook to properly upgrade a single-site indexer cluster and search head cluster using the splunk role from ansible-role-for-splunk
- hosts:
    - splunk_clustermaster
    - splunk_clustermanager
  become: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  roles:
    - ../roles/splunk
  vars:
    deployment_task: check_splunk.yml

- hosts:
    - splunk_dmc
    - splunk_licensemaster
    - splunk_shdeployer
    - splunk_deploymentserver
  become: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  roles:
    - ../roles/splunk
  vars:
    deployment_task: check_splunk.yml

- hosts:
    - splunk_search
  serial: 50
  become: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  roles:
    - ../roles/splunk
  vars:
    deployment_task: check_splunk.yml

- hosts:
    - splunk_clustermaster
    - splunk_clustermanager
  become: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  roles:
    - ../roles/splunk
  vars:
    deployment_task: set_maintenance_mode.yml
    state: enable

- hosts:
    - splunk_indexer
  serial: 100
  become: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  roles:
    - ../roles/splunk
  vars:
    deployment_task: check_splunk.yml

- hosts:
    - splunk_clustermaster
    - splunk_clustermanager
  become: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  roles:
    - ../roles/splunk
  vars:
    deployment_task: set_maintenance_mode.yml
    state: disable
